default_language_version:
  python: python3

repos:
  # Should be enabled either yapf or black once this branch is merged
  # - repo: https://github.com/google/yapf.git
  #   rev: v0.40.1
  #   hooks:
  #     - id: yapf

  - repo: https://github.com/psf/black.git
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # - repo: https://github.com/google/pytype
  #   # Ruff version.
  #   rev: 2023.09.11
  #   hooks:
  #     - id: pytype
  #       # args:
  #       #   - --config=pyproject.toml
