model: meta-llama/Llama-2-7b-chat-hf
prompt: "Hello, I'm a llama."
MTK_PLAYGROUND_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4OTE3MTIzLCJpYXQiOjE2OTgzMTIzMjMsImp0aSI6IjdlNDA3YmRkMGU3OTQzMmM4MmJhYjkwYjQ1MDcyNGEwIiwic3ViIjoiZHM5MDY2NTkiLCJkb21haW4iOiJvYSIsImlzcyI6Im1lZGlhdGVrLmluYyJ9.N2c0u4L3P80h2u3eR9GmWlk8Q_mK2SgyrQF5kupiAj8
