name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    container: catthehacker/ubuntu:act-latest  # Uncomment it if you use it on Gitea

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.9"

    timeout-minutes: 10

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # Enable these three lines if you run on act
          token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install sh
          git clone https://gitea.mediatek.inc/AITH/ai-thermal-simulator-pl-dataset.git

      - name: List dependencies
        run: |
          python -m pip list

      - name: Run pytest
        run: |
          pytest -v
